//! Kamosu — a self-hosted cookbook where people and software agents are equal users.
//!
//! The shape of the whole program (ADR 0001): every Operation is declared once in
//! the [`catalogue`] — its name, its input, its output, the permission it requires,
//! and the function that performs it. Both Doors are generated by walking that one
//! declaration list, so Parity is how the program is assembled, not a rule anyone
//! has to remember. Authorisation is checked once, in [`core`], beneath both Doors;
//! a permission check written inside a Door is a bug.

pub mod catalogue;
pub mod config;
pub mod core;
pub mod cover;
pub mod cover_faces;
pub mod db;
pub mod design_tokens;
pub mod http_min;
pub mod interface;
pub mod jobs;
pub mod language;
pub mod mcp_door;
pub mod meaning;
pub mod operations;
pub mod pairing;
pub mod photographs;
pub mod reading;
pub mod share_card;
pub mod share_page;
pub mod units;
pub mod web_door;
pub mod web_import;

pub use core::{ErrorKind, OpError};

use std::sync::Arc;

/// The whole served application, assembled once.
///
/// Both Doors carry the Catalogue; the design tokens, the Share Link page and
/// the interface ride beside them — stylesheet, fonts, icons, one
/// server-rendered page and the compiled app, never Operations. **The interface
/// is merged last** because it owns the fallback: a path is a screen only once
/// nothing else has claimed it.
///
/// The Share Link page (#65) *consumes* an Operation and is not one, which is
/// what leaves Parity untouched: `/s/<token>` is no more a route into the
/// Catalogue than `/assets/app.css` is.
///
/// This exists as one function so the binary and the behaviour suite cannot
/// assemble the app differently. A test that served a different arrangement
/// from the one shipped would be testing something nobody runs.
pub fn app(core: Arc<core::Core>) -> axum::Router {
    let core_for_shares = core.clone();
    web_door::router(core.clone())
        .merge(mcp_door::router(core))
        .merge(design_tokens::router())
        .merge(share_page::router(core_for_shares))
        .merge(interface::router())
}

/// The MCP revision this build speaks: stateless, no handshake.
pub const MCP_PROTOCOL_VERSION: &str = "2026-07-28";

/// The standard long-running-task extension carried at the MCP door: asking for
/// a Job answers a CreateTaskResult, polled back through ordinary Operations.
pub const MCP_TASKS_EXTENSION: &str = "io.modelcontextprotocol/tasks";
