//! Kamosu — a self-hosted cookbook where people and software agents are equal users.
//!
//! The shape of the whole program (ADR 0001): every Operation is declared once in
//! the [`catalogue`] — its name, its input, its output, the permission it requires,
//! and the function that performs it. Both Doors are generated by walking that one
//! declaration list, so Parity is how the program is assembled, not a rule anyone
//! has to remember. Authorisation is checked once, in [`core`], beneath both Doors;
//! a permission check written inside a Door is a bug.

pub mod catalogue;
pub mod config;
pub mod core;
pub mod db;
pub mod design_tokens;
pub mod http_min;
pub mod jobs;
pub mod mcp_door;
pub mod operations;
pub mod web_door;

pub use core::{ErrorKind, OpError};

/// The MCP revision this build speaks: stateless, no handshake.
pub const MCP_PROTOCOL_VERSION: &str = "2026-07-28";

/// The standard long-running-task extension carried at the MCP door: asking for
/// a Job answers a CreateTaskResult, polled back through ordinary Operations.
pub const MCP_TASKS_EXTENSION: &str = "io.modelcontextprotocol/tasks";
