/**
 * What the interface is linted for.
 *
 * This is deliberately a narrow net. `svelte-check` already runs in strict mode
 * with accessibility warnings treated as failures (ADR 0012), and TypeScript is
 * strict with `checkJs` on, so most of what ESLint usually catches is caught
 * before it gets here. What is left, and what this config is for, is the part a
 * type checker structurally cannot see: unused bindings, and Svelte's own
 * runtime footguns — a mutated prop, a misused `{@html}`, a store read that
 * silently never updates.
 *
 * Layout is not in scope. Prettier owns that (ui/.prettierrc.yaml), and the two
 * prettier configs at the bottom switch off every rule here that would have an
 * opinion about it.
 */

import js from '@eslint/js';
import ts from 'typescript-eslint';
import svelte from 'eslint-plugin-svelte';
import prettier from 'eslint-config-prettier/flat';
import globals from 'globals';

export default ts.config(
	{
		// The same exclusions as ui/.prettierignore, for the same reason: these
		// files are generated, and nothing is served by reporting on code no
		// human will edit. Keep the two lists in step.
		ignores: [
			'src/lib/api/catalogue.ts', // generated by `just client`
			'src/lib/paraglide/', // compiled from messages/ by inlang
			'build/',
			'.svelte-kit/',
		],
	},

	js.configs.recommended,
	ts.configs.recommended,
	svelte.configs.recommended,

	{
		languageOptions: {
			globals: {
				// Screens run in a browser; the generator scripts and vite config
				// run in Node. One flat list rather than two file-scoped blocks —
				// the type checker is what actually catches a wrong environment.
				...globals.browser,
				...globals.node,
			},
		},
	},

	{
		files: ['**/*.svelte', '**/*.svelte.ts', '**/*.svelte.js'],
		languageOptions: {
			parserOptions: {
				// svelte-eslint-parser handles the component; the script block
				// inside it is TypeScript and needs its own parser.
				parser: ts.parser,
				extraFileExtensions: ['.svelte'],

				// The documented setup imports ./svelte.config.js here. Kamosu has
				// none — SvelteKit is configured inline in vite.config.ts, which is
				// where `runes: true` is really decided. Restated rather than
				// imported because eslint.config.js cannot import a .ts file
				// without a loader, and one boolean duplicated is a smaller price
				// than a build file rearranged to suit a linter. If runes mode ever
				// changes, it changes in vite.config.ts first and here second.
				svelteConfig: { compilerOptions: { runes: true } },
			},
		},
	},

	{
		rules: {
			// Off because Kamosu is always served from the root. `resolve()`
			// exists to prepend `config.kit.paths.base`, and this app has no
			// base to prepend: ADR 0028 publishes one port serving one
			// directory, and ADR 0033 holds the reverse proxy to carrying bytes
			// and terminating TLS — not rewriting paths. Turn this back on the
			// day Kamosu is meant to be mountable under a sub-path, and add
			// `resolve()` to every href and goto() at that point.
			'svelte/no-navigation-without-resolve': 'off',

			// Off because this codebase never mutates a reactive collection in
			// place. Every update copies and reassigns —
			//
			//     const next = new Set(open);
			//     if (next.has(key)) next.delete(key); else next.add(key);
			//     open = next;
			//
			// — and reassignment is what makes `$state` react, so a plain Set is
			// correct here. The rule cannot see that distinction: it fires on
			// the `new Set(...)` regardless of what happens next, which in this
			// codebase means it is wrong every time and would go on being wrong
			// for correct new code.
			//
			// The caveat it was guarding is real, so keep it in mind: `$state`
			// does NOT deep-proxy a Map or a Set. `open.add(key)` on its own
			// updates nothing and renders nothing. If in-place mutation is ever
			// what you want, reach for SvelteSet or SvelteMap from
			// `svelte/reactivity` rather than dropping the copy.
			'svelte/prefer-svelte-reactivity': 'off',
		},
	},

	// Last, and in this order. eslint-config-prettier switches off the core and
	// TypeScript stylistic rules; svelte.configs.prettier does the same for the
	// Svelte-specific ones, which the first config knows nothing about. Without
	// both, ESLint and Prettier disagree about a file and neither one wins.
	prettier,
	svelte.configs.prettier,
);
