/**
 * Generate the Cover's faces for the Core.
 *
 * A Cover is what leads a recipe with no Main Photo (#46), and until #65 it was
 * drawn in exactly one place: the Svelte app. The Share Link page is rendered
 * by the Rust server as plain HTML (ADR 0012, ADR 0026), so the same eight dyes
 * and eight shapes now have to be reachable from Rust as well — and a Cover
 * that differs between the two would break the one promise `cover.ts` makes,
 * that a Lineage wears the same face everywhere it is drawn.
 *
 * So the data is not copied by hand. `ui/src/lib/cover/shapes.ts` and the dye
 * list in `ui/src/lib/cover/cover.ts` stay the single source, and this writes
 * them out as Rust. The *arithmetic* — the hash, the blending, which dye and
 * shape a Lineage id resolves to — is written once in each language and pinned
 * against shared fixtures by `src/cover.rs`'s tests, because twenty lines of
 * plain arithmetic read better hand-written than generated.
 *
 * Usage:  node ./generate-cover.mjs
 *         OUT=path/to/cover_faces.rs node ./generate-cover.mjs
 *
 * Never edit the output. Change the TypeScript and run `just cover`;
 * `just check` fails if the committed copy has drifted.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { registerHooks } from 'node:module';
import { dirname, resolve } from 'node:path';

// The app's own modules import each other without a file extension, which is
// what Vite and `svelte-check` expect and what every other file here does.
// Node resolves extensions only for JavaScript, so rather than making the
// source files unlike their neighbours for the sake of this script, the script
// does the extension-adding — the one place that needs it.
registerHooks({
	resolve(specifier, context, next) {
		try {
			return next(specifier, context);
		} catch (error) {
			if (!specifier.startsWith('.')) throw error;
			return next(`${specifier}.ts`, context);
		}
	},
});

const { DYES } = await import('./src/lib/cover/cover.ts');
const { PASTA_SHAPES } = await import('./src/lib/cover/shapes.ts');

const DEFAULT_OUT = '../src/cover_faces.rs';

/** A Rust string literal. The inputs are hex colours, keys and SVG path data —
 *  no quotes or backslashes occur in any of them, and this asserts that rather
 *  than escaping, so a shape that grew one is a failed build. */
function rust(text) {
	if (/["\\]/.test(text)) {
		throw new Error(`cover data must not contain quotes or backslashes: ${text}`);
	}
	return `"${text}"`;
}

function generate() {
	const out = [];
	out.push("//! The Cover's faces: the eight dyes and the eight pasta shapes (#46).");
	out.push('//!');
	out.push('//! GENERATED by `ui/generate-cover.mjs` from `ui/src/lib/cover/`, which is');
	out.push('//! where the choice lives. Never edit this file: change the TypeScript and');
	out.push('//! run `just cover`. `just check` fails if this copy has drifted.');
	out.push('//!');
	out.push('//! Order is part of the contract in both languages. A Cover is chosen by');
	out.push('//! index, so reordering either list repaints every recipe already written.');
	out.push('//!');
	out.push('//! The two lists carry `#[rustfmt::skip]`, for the same reason');
	out.push('//! `ui/.prettierignore` excludes the generated files on that side: the');
	out.push('//! freshness gate compares this file byte-for-byte against a fresh');
	out.push('//! regeneration, so a formatter reshaping it afterwards would fail the');
	out.push('//! build every time with nothing actually wrong.');
	out.push('');
	out.push('/// One dye: the ground a Cover is drawn on.');
	out.push('pub struct Dye {');
	out.push("    pub key: &'static str,");
	out.push('    /// The traditional name, for tests and for people reading the code.');
	out.push("    pub name: &'static str,");
	out.push("    pub hex: &'static str,");
	out.push('}');
	out.push('');
	out.push('/// One pasta shape, authored in a `0 0 100 100` viewBox with absolute');
	out.push('/// coordinates and closed subpaths only.');
	out.push('pub struct PastaShape {');
	out.push("    pub key: &'static str,");
	out.push("    pub name: &'static str,");
	out.push('    /// Filled with the lighter tone of the dye.');
	out.push("    pub body: &'static [&'static str],");
	out.push('    /// Ridges and grooves, filled with the dye at partial opacity.');
	out.push("    pub detail: &'static [&'static str],");
	out.push('}');
	out.push('');
	out.push('#[rustfmt::skip]');
	out.push(`pub const DYES: &[Dye] = &[`);
	for (const dye of DYES) {
		out.push(`    Dye { key: ${rust(dye.key)}, name: ${rust(dye.name)}, hex: ${rust(dye.hex)} },`);
	}
	out.push('];');
	out.push('');
	out.push('#[rustfmt::skip]');
	out.push(`pub const PASTA_SHAPES: &[PastaShape] = &[`);
	for (const shape of PASTA_SHAPES) {
		out.push('    PastaShape {');
		out.push(`        key: ${rust(shape.key)},`);
		out.push(`        name: ${rust(shape.name)},`);
		for (const [field, paths] of [
			['body', shape.body],
			['detail', shape.detail],
		]) {
			if (paths.length === 0) {
				out.push(`        ${field}: &[],`);
				continue;
			}
			out.push(`        ${field}: &[`);
			for (const d of paths) out.push(`            ${rust(d)},`);
			out.push('        ],');
		}
		out.push('    },');
	}
	out.push('];');
	out.push('');
	return out.join('\n');
}

const target = resolve(process.env.OUT ?? DEFAULT_OUT);
mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, generate());
