// Reading a design token out of the generated stylesheet.
//
// `assets/app.css` is the one source of what Kamosu looks like (AGENTS.md,
// issue #80). Anything else that needs a colour — the icon rasteriser, the web
// manifest — reads it from there rather than keeping a copy, so there is no
// second place a colour can be changed and no way for one to fall behind.
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

/** The default stylesheet: the committed one the binary embeds. */
export const DEFAULT_STYLESHEET = path.join(root, 'assets/app.css');

/**
 * Every custom property declared in the stylesheet's theme layer.
 *
 * The generated file declares exactly one `:root, :host { … }` block. Values
 * contain commas and parens but never a semicolon, so splitting on ';' is safe.
 */
export function readTokens(stylesheet = DEFAULT_STYLESHEET) {
	const css = readFileSync(stylesheet, 'utf8');
	const start = css.indexOf(':root, :host {');
	const end = css.indexOf('}', start);
	if (start === -1 || end === -1) {
		throw new Error(`no theme block in ${stylesheet} — was it generated by 'just css'?`);
	}
	const tokens = new Map();
	for (const declaration of css.slice(start, end).split(';')) {
		const [name, ...rest] = declaration.split(':');
		if (name.trim().startsWith('--')) tokens.set(name.trim(), rest.join(':').trim());
	}
	return tokens;
}

/** One token, or a loud failure. A missing colour must never become a silent black. */
export function token(name, stylesheet = DEFAULT_STYLESHEET) {
	const value = readTokens(stylesheet).get(name);
	if (!value) throw new Error(`${name} is not declared in ${stylesheet}`);
	return value;
}
